Pin to openshift <= 0.8.9
It looks like 0.9.0 has released, and it seems like it requires
creating a dynamic client now.  We're seeing jobs using nodepool fail
with

 File "... /nodepool/driver/openshift/provider.py", line 21, in <module>
   from openshift import client as os_client
 ImportError: cannot import name 'client' from 'openshift'

This does break things like the project-config gate.  Pin to 0.8.9 for
now until it is fixed.

Change-Id: Ie9ccb56f987b4d05c6fe9d4938ca74a110f55653